[kodama]
trees = "trees"
assets = "assets"
base-url = "/"

[build]
typst-root = "./trees"
short-slug = false
pretty-urls = false
footer-mode = "embed"
inline-css = false
output = "./publish"

[serve]
# edit = "vscode://file/"
output = "./.cache/publish"
command = ["miniserve", "<output>", "--index", "index.html", "--pretty-urls"]
